import java.io.File;
import java.io.Writer;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nirf' at '11/21/16 8:28 AM' with Gradle 2.4
 *
 * @author nirf, @date 11/21/16 8:28 AM
 */
public class StudentsPrinter {

    private final Writer writer;

    public StudentsPrinter(Writer writer){
        this.writer = writer;
    }

    void printStudents(File csvFile) {
        //YOUR CODE SHOULD COME HERE
    }


}
