import org.junit.Test;

import java.io.File;
import java.io.StringWriter;
import java.io.Writer;

import static org.junit.Assert.assertEquals;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nirf' at '11/21/16 8:28 AM' with Gradle 2.4
 *
 * @author nirf, @date 11/21/16 8:28 AM
 */
public class StudentPrinterTest {

    @Test
    public void testExampleInput() {
        Writer writer = new StringWriter();
        StudentsPrinter studentsPrinter = new StudentsPrinter(writer);
        studentsPrinter.printStudents(new File("test_input.csv"));
        String output = writer.toString();
        assertEquals(expected(), output);
    }

    private String expected() {
        return
        "1,Erez,ERROR" + "\n" +
        "2.Netanel,82.5,Math,English" + "\n" +
        "3,Ronen,80,English";
    }
}
